---
title: "Analysis of the effect of Character Sentiment on TV show ratings"
execute:
  echo: false
format: html
editor: visual
---

## Abstract




```{r}
#| output: false
library(dplyr)
library(ggplot2)
original_data <- read.csv("../../data/office_sentiment .csv") 
```



Cleaning Data

```{r}
#| echo: true
data <- na.omit(original_data)
data <- data |> mutate(average_score = sentimentr_score)
```


Rating vs Sentiment 
```{r}
filtered_data <- data |>
  group_by(character) |>
  filter(n() > 45) |>
  ungroup()

episode_data <- data |> 
  distinct(season, episode) |>
  mutate(episode_index = row_number())

new_data <- merge(data, episode_data, by = c("season", "episode")) 

average_episode <- new_data |>
  group_by(episode_index) |>
  summarise(mean_score = mean(average_score, na.rm = TRUE)) |>
  left_join(new_data |> select(episode_index, imdb_rating) |> distinct(), by = "episode_index")

ggplot(average_episode, title="All Characters", aes(x = mean_score, y = imdb_rating)) + geom_point() + geom_smooth(formula = y ~ x,method = "lm", se = FALSE)
```

filter to only main characters

```{r}

data <- data |>
  group_by(character) |>
  filter(n() > 45) |>
  ungroup()
episode_data <- data |> 
  distinct(season, episode) |>
  mutate(episode_index = row_number())
new_data <- merge(data, episode_data, by = c("season", "episode")) 
average_episode <- new_data |>
  group_by(episode_index) |>
  summarise(mean_score = mean(average_score, na.rm = TRUE)) |>
  left_join(new_data |> select(episode_index, imdb_rating) |> distinct(), by = "episode_index")
ggplot(average_episode,aes(x = mean_score, y = imdb_rating)) + geom_point() + geom_smooth(formula = y ~ x, method = "lm", se = FALSE) +labs(title="Only Main Characters")
```